### PR TITLE
Limit name maximum characters

### LINKED ISSUE #202: [PE-D][Tester E] The app fail to show full detail of an extremly long name
Description: When a patient has an extremely long name, the app should show its full name. Currently, the extremely long name will be shown as ...

Steps to reproduce: add a patient using "add -IC S1234561Z -N Seraphina Celestielle Amaranthine Isabella Rose Elara Montmorency von Silverthorne Wintervale Nightshade Aurelia Callidora Everwyn Astraea Lysandra Moonshadow the Third Duchess of the Starlit Realms Keeper of the Eternal Flame High Enchantress of the Ninefold Sanctum Heir to the Thrones of Aetherion -P 81234567 -DOB 02/02/1995"

Expected: The GUI will show its full name

Actual: Some parts of the name cannot be shown despite maximize the size of the app

Screenshots:

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: zlllllr/ped#6

### PR DESCRIPTION
**Pull request by Codekrodile**
fixes #202

### CODE REVIEW

File: src/test/java/seedu/address/model/person/NameTest.java [hunk 1]
```diff
@@ -29,13 +29,15 @@ public void isValidName() {
...
+        assertFalse(Name.isValidName(
+                    "aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeeeffffffffffggggggg")); // exceed max char
 
         // valid name
         assertTrue(Name.isValidName("peter jack")); // alphabets only
         assertTrue(Name.isValidName("12345")); // numbers only
         assertTrue(Name.isValidName("peter the 2nd")); // alphanumeric characters
         assertTrue(Name.isValidName("Capital Tan")); // with capital letters
-        assertTrue(Name.isValidName("David Roger Jackson Ray Jr 2nd")); // long names
+        assertTrue(Name.isValidName("Maximiliano Featherstone Worthington Benedictus de la Cruz Xavier")); // long names
```
Comment (Hugo-Chia) [inline src/test/java/seedu/address/model/person/NameTest.java:40]: I like that you included new test to ensure the length validation works as intended.
