### PR TITLE
Fix viewp nric insensitivity

### LINKED ISSUE #117: viewp NRIC should be case insensitive
viewp -IC flag should be case insensitive

### PR DESCRIPTION
**Pull request by Codekrodile**
fixes #117

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ViewpCommandParser.java [hunk 1]
```diff
@@ -23,7 +23,7 @@ public ViewpCommand parse(String args) throws ParseException {
             throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, ViewpCommand.MESSAGE_USAGE));
         }
 
-        String nric = argMultimap.getValue(PREFIX_NRIC).get();
+        String nric = argMultimap.getValue(PREFIX_NRIC).get().toUpperCase();
```
Comment (Hugo-Chia) [inline src/main/java/seedu/address/logic/parser/ViewpCommandParser.java:26]: LGTM, this should fix the issue
