### PR TITLE
Fix ViewpCommandParser to detect dup parameter

### LINKED ISSUE #143: Viewp command duplicate parameter
Image

should check for duplicate parameter

### PR DESCRIPTION
**Pull request by Codekrodile**
fix #143

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ViewpCommandParser.java [hunk 1]
```diff
@@ -23,6 +23,7 @@ public ViewpCommand parse(String args) throws ParseException {
             throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, ViewpCommand.MESSAGE_USAGE));
         }
 
+        argMultimap.verifyNoDuplicatePrefixesFor(PREFIX_NRIC);
         String nric = argMultimap.getValue(PREFIX_NRIC).get().toUpperCase();
```
Comment (Hugo-Chia) [inline src/main/java/seedu/address/logic/parser/ViewpCommandParser.java:27]: Could we verify nric with ParserUtil?

Comment (Codekrodile) [reply src/main/java/seedu/address/logic/parser/ViewpCommandParser.java]: Good idea! ive just updated it!

File: src/main/java/seedu/address/logic/parser/ViewpCommandParser.java [hunk 2]
```diff
@@ -23,7 +23,8 @@ public ViewpCommand parse(String args) throws ParseException {
             throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, ViewpCommand.MESSAGE_USAGE));
         }
 
-        String nric = argMultimap.getValue(PREFIX_NRIC).get().toUpperCase();
+        argMultimap.verifyNoDuplicatePrefixesFor(PREFIX_NRIC);
```
Comment (Hugo-Chia) [inline src/main/java/seedu/address/logic/parser/ViewpCommandParser.java:26]: Great work, ensuring NRIC parameter is not duplicated
