### PR TITLE
Disallow duplicate appointments

### LINKED ISSUE #198: [PE-D][Tester B] Duplicate appointments at identical datetime can be added for same patient
### Steps to reproduce
1. Repeat the command `addappt -IC S9132623Z -D 25/06/2025 09:00` multiple times

### Expected
Some form of error indicating that an appointment with the same datetime already exists.

### Actual
Addition is allowed

### Suggestion
Employ some form of duplicate checking

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: kubrian/ped#3

### LINKED ISSUE #216: [PE-D][Tester D] Ability to add appointments at the same timing for a patient
### Description
A patient should not be able to have more than one appointment at the exact same date and time as it does not make sense, especially in this context.

**Expected:** Patient cannot have more than one appointment at the same date and time.
**Actual:** They can.

---

**Screenshot:**

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: wenruu/ped#9

### LINKED ISSUE #228: [PE-D][Tester E] Duplicate in appointments
Description: The same appointments can be added to the same patient

Steps to reproduce: Add appointment using  "addappt -IC S1234567Z -D 25/06/2025 00:00" multiple times

Expected: Same appointments should not be allowed to added multiple times

Actual: The same appointments are be added

Screenshots:

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: zlllllr/ped#15

### PR DESCRIPTION
**Pull request by AerollingOverDeepBlueSeas**
Added additional check for existence of appointment before a potentially-duplicate appointment is added.
Fixes #228 
Fixes #216 
Fixes #198

### CODE REVIEW

File: src/test/java/seedu/address/model/appointment/AppointmentListTest.java [hunk 1]
```diff
@@ -48,4 +49,13 @@ public void sortAppointments_multipleAppointments_chronologicalOrder() {
         assertEquals("01/01/2025 15:00", appointmentList.getAppointments().get(0).toString());
         assertEquals("02/01/2025 16:00", appointmentList.getAppointments().get(1).toString());
     }
+
+    @Test
+    public void containsAppointment_validAppointment_success() {
+        AppointmentList appointmentList = new AppointmentList();
+        appointmentList.addAppointment("01/01/2028 15:00");
+        assertTrue(appointmentList.hasAppointment(Appointment.createAppointment("01/01/2028 15:00")));
+        assertFalse(appointmentList.hasAppointment(Appointment.createAppointment("02/02/2028 15:00")));
```
Comment (Hugo-Chia) [inline src/test/java/seedu/address/model/appointment/AppointmentListTest.java:58]: I like that you wrote a test verifying the 2nd (duplicate) appointment should fail. This should prevent future bugs related to duplicate appointment from being introduced.

File: src/main/java/seedu/address/model/appointment/Appointment.java [hunk 2]
```diff
@@ -31,4 +31,12 @@ public String toString() {
         DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
         return apptDateTime.format(formatter);
     }
+
+    @Override
+    public boolean equals(Object o) {
+        if (o instanceof Appointment other) {
+            return this.apptDateTime.equals(other.apptDateTime);
```
Comment (Hugo-Chia) [inline src/main/java/seedu/address/model/appointment/Appointment.java:38]: I like that the validation uses the LocalDateTime object to compare instead of a String representation comparison as that may sometimes result in issues.
